### ISSUE TITLE
Command 'Active ECharts Extension' resulted in an error 

### ISSUE THREAD

**Issue by Justineo** [susiwen8/echarts-vscode-extension#70]
![image](https://user-images.githubusercontent.com/1726061/81470839-99312e00-921f-11ea-8e93-6066bbe3d4bc.png)

**Comment by susiwen8** [comment]
@Justineo  谢谢反馈，我追查下

**Comment by susiwen8** [comment]
@Justineo 能把错误信息提供下吗，vscode 版本呢？

**Comment by susiwen8** [comment]
@Justineo 能把错误信息提供下吗，vscode 版本呢？

**Comment by Justineo** [comment]
错误信息：

```
[2020-05-09 18:23:11.131] [exthost] [error] SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (12:0)
	at W.ee.raise (/Users/justineo/.vscode/extensions/susiwen8.vscode-echarts-extension-0.2.0/dist/extension.js:1:73701)
	at W.U.parseStatement (/Users/justineo/.vscode/extensions/susiwen8.vscode-echarts-extension-0.2.0/dist/extension.js:1:34460)
	at W.U.parseTopLevel (/Users/justineo/.vscode/extensions/susiwen8.vscode-echarts-extension-0.2.0/dist/extension.js:1:31935)
	at W.parse (/Users/justineo/.vscode/extensions/susiwen8.vscode-echarts-extension-0.2.0/dist/extension.js:1:28489)
	at Function.W.parse (/Users/justineo/.vscode/extensions/susiwen8.vscode-echarts-extension-0.2.0/dist/extension.js:1:29221)
	at Module.Ne (/Users/justineo/.vscode/extensions/susiwen8.vscode-echarts-extension-0.2.0/dist/extension.js:1:113285)
	at Object.n.checkCode (/Users/justineo/.vscode/extensions/susiwen8.vscode-echarts-extension-0.2.0/dist/extension.js:1:9047)
	at /Users/justineo/.vscode/extensions/susiwen8.vscode-echarts-extension-0.2.0/dist/extension.js:16:2440543
	at e._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:627:894)
	at e.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:628:295)
	at e._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:788:757)
	at e._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:788:449)
	at e._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:787:120)
	at e._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:785:970)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:784:213
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:67)
	at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:232:615)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:957:179
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:67)
	at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:232:615)
	at t.PersistentProtocol._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:237:17)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:234:155
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:67)
	at p.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:230:129)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:229:483
	at Socket.t (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:238:565)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17) echarts.activate
```

VSCode 版本：

```
Version: 1.45.0
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T15:57:33.467Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.0.0
```

**Comment by susiwen8** [comment]
@Justineo 收到

**Comment by susiwen8** [comment]
@Justineo 问题已修复，没有设置 `acorn.parse` 的 `sourceType` 为 `module`
